In [1]:
import numpy as np
x = np.array([1,2,3])

In [2]:
x.__class__#클래스 이름 표시

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [5]:
W = np.array([[1,2,3],[4,5,6]])

In [6]:
W.shape

(2, 3)

In [7]:
W.ndim

2

In [8]:
W

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
X = [[0,1,2],[3,4,5]]

In [12]:
X

[[0, 1, 2], [3, 4, 5]]

In [10]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
A = np.array([[1,2],[3,4]])

In [14]:
A*10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2],[3,4]])

In [16]:
b = np.array([10,20])

In [17]:
A*b

array([[10, 40],
       [30, 80]])

In [18]:
a = np.array([1,2,3])

In [19]:
b = np.array([4,5,6])

In [20]:
np.dot(a,b)

32

In [22]:
#행렬의 내적
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [23]:
A*B

array([[ 5, 12],
       [21, 32]])

In [25]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [26]:
#완전 연결계층에 의한 변환의 미니배치 버전(선형 변환)
import numpy as np
W1 = np.random.randn(2,4)#가중치 2x4
b1 = np.random.randn(4)#편향 1x4
x = np.random.randn(10,2)#입력 10x2
h = np.matmul(x,W1)+b1

In [27]:
#S모양 곡선(비선형 변환)
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [29]:
#시그모이드를 사용하여 은닉층 뉴런을 변환(비선형 변환)
a= sigmoid(h)

In [30]:
#신경망 추론 전체 그림
import numpy as np

def sigmoid(x):#시그모이드
    return 1/(1+np.exp(-x))

x = np.random.randn(10,2)#10x2입력층: 2차원 데이터 10개가 미니배치로 처리됨
W1 = np.random.randn(2,4)#2x4 가중치
b1 = np.random.randn(4)#1x4 편향
W2 = np.random.randn(4,3)#4x3 가중치
b2 = np.random.randn(3)

h = np.matmul(x,W1)+b1#10x4 은닉층
a = sigmoid(h)#10x4 완전 연결 계층
s = np.matmul(a,W2)+b2#10x3 최종 출력(3 클래스 분류)