In [1]:
import numpy as np
x = np.array([1,2,3])

In [2]:
x.__class__#클래스 이름 표시

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [5]:
W = np.array([[1,2,3],[4,5,6]])

In [6]:
W.shape

(2, 3)

In [7]:
W.ndim

2

In [8]:
W

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
X = [[0,1,2],[3,4,5]]

In [12]:
X

[[0, 1, 2], [3, 4, 5]]

In [10]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])