In [1]:
import numpy as np
x = np.array([1,2,3])

In [2]:
x.__class__#클래스 이름 표시

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [5]:
W = np.array([[1,2,3],[4,5,6]])

In [6]:
W.shape

(2, 3)

In [7]:
W.ndim

2

In [8]:
W

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
X = [[0,1,2],[3,4,5]]

In [12]:
X

[[0, 1, 2], [3, 4, 5]]

In [10]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
A = np.array([[1,2],[3,4]])

In [14]:
A*10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2],[3,4]])

In [16]:
b = np.array([10,20])

In [17]:
A*b

array([[10, 40],
       [30, 80]])

In [18]:
a = np.array([1,2,3])

In [19]:
b = np.array([4,5,6])

In [20]:
np.dot(a,b)

32

In [22]:
#행렬의 내적
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [23]:
A*B

array([[ 5, 12],
       [21, 32]])

In [25]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [26]:
#완전 연결계층에 의한 변환의 미니배치 버전(선형 변환)
import numpy as np
W1 = np.random.randn(2,4)#가중치 2x4
b1 = np.random.randn(4)#편향 1x4
x = np.random.randn(10,2)#입력 10x2
h = np.matmul(x,W1)+b1

In [27]:
#S모양 곡선(비선형 변환)
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [29]:
#시그모이드를 사용하여 은닉층 뉴런을 변환(비선형 변환)
a= sigmoid(h)

In [30]:
#신경망 추론 전체 그림
import numpy as np

def sigmoid(x):#시그모이드
    return 1/(1+np.exp(-x))

x = np.random.randn(10,2)#10x2입력층: 2차원 데이터 10개가 미니배치로 처리됨
W1 = np.random.randn(2,4)#2x4 가중치
b1 = np.random.randn(4)#1x4 편향
W2 = np.random.randn(4,3)#4x3 가중치
b2 = np.random.randn(3)

h = np.matmul(x,W1)+b1#10x4 은닉층
a = sigmoid(h)#10x4 완전 연결 계층
s = np.matmul(a,W2)+b2#10x3 최종 출력(3 클래스 분류)

In [31]:
class Sigmoid:#시그모이드 함수를 클래스로 구현
    def __init__(self):
        self.params = []#학습하는 매개변수 없음
    
    def forward(self, x):
        return 1/(1+np.exp(-x))

In [32]:
class Affine:#완전 연결 계층 클래스로 구현
    def __init__(self,W,b):#초기화
        self.params = [W,b]#가중치와 편향
    
    def forward(self,x):#순전차 처리 구현
        W,b = self.params
        out = np.matmul(x,W)+b
        return out

In [41]:
#Two Layer Net 구현
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):#가중치 초기화
        I, H, O = input_size,hidden_size, output_size#3개의 계층 생성
        
        #가중치와 편향 초기화
        W1 = np.random.randn(I,H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H,O)
        b2 = np.random.randn(O)
        
        #계층 생성
        self.layers = [
            Affine(W1,b1),
            Sigmoid(),
            Affine(W2,b2)
        ]
        
        #모든 가중치를 리스트에 모은다
        self.params = []
        for layer in self.layers:
            self.params += layer.params
    
    def predict(self, x):#추론 처리
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [42]:
#리스트 결합
a = ['A','B']
a+= ['C','D']

In [43]:
a

['A', 'B', 'C', 'D']

In [44]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)#input_size, hidden_size, output_size
s = model.predict(x)
s#입력 데이터 x에 대한 점수(ㄴ)

array([[ 0.48988136, -1.98812148,  3.00120095],
       [ 0.6765205 , -1.06528948,  4.19082399],
       [ 0.72285721, -0.98341831,  4.34754096],
       [ 0.82685718, -0.89374449,  4.40530989],
       [ 0.66449036, -1.08483364,  4.0748879 ],
       [ 1.01580743, -0.85571633,  3.90414502],
       [ 0.5097578 , -1.91111883,  3.33262692],
       [ 0.87903668, -1.35777454,  3.81872853],
       [ 1.0263118 , -0.68828592,  3.96687848],
       [ 0.28436914, -2.19822323,  2.45952867]])

### 소프트맥스 함수
$$y_k \frac{exp(s_k)}{ \sum_{i=1}^n exp(s_i)}$$
<b>출력이 총 $n$개일 때, $k$번째의 출력 $y_k$를 구하는 계산식</b><br>
<b>$y_k$: $k$번째 클래스에 해당하는 소프트맥스 함수의 출력</b>

<br><br>
### 교차 엔트로피 오차의 수식
$$L = -\sum_k t_klogy_k$$
정답 레이블은 $t = [0,0,1]$과 같이 원핫 벡터로 표기

<br><br>

### 미니 배치 처리를 고려한 오차의 식
$$L = -\frac{1}{N}\sum_n\sum_k t_{nk}logy_{nk}$$
:평균 손실 함수<br><br>
데이터 개수:N개, $t_{nk}$: n번째 데이터의 k차원째의 값, $y_{nk}$: 신경망의 출력, $t_{nk}$: 정답 레이블

In [47]:
#Repeat 노드
D, N = 8,7

#입력
x = np.random.randn(1,D)

#순전파
y = np.repeat(x,N,axis = 0)#원소 복제 수행

#무작위 기울기
dy = np.random.randn(N,D)

#역전파
dx = np.sum(dy, axis = 0,#총합
           keepdims=True)#2차원 배열 차원 수 유지

In [48]:
dx

array([[ 5.39809163, -6.50412858,  1.57210402, -1.85534185, -2.12816353,
        -1.98131893,  3.16830447,  2.32178235]])

In [49]:
dy

array([[ 0.56952598, -1.22725653, -1.24556488,  0.13704173,  1.21360177,
        -1.96168425,  0.82642681,  1.23160423],
       [ 1.63526847, -1.54056466,  0.62169324, -0.09625278, -0.73294248,
         0.7018978 ,  1.14968002, -1.20519641],
       [ 0.90876329,  0.04510618, -1.38657889,  0.94230008, -1.37633776,
        -0.61148481, -0.33193171,  0.36360305],
       [-0.33741463, -0.6803668 ,  0.72781723, -0.25635209,  1.21623509,
        -2.07378438,  0.53632318,  1.24198267],
       [ 0.48747785, -1.54608446,  2.02442711, -1.69605654, -1.58236084,
         1.13409802, -0.1153853 ,  1.62164953],
       [ 1.8302467 ,  0.50031148,  0.19776204, -1.45555192, -0.70033747,
         0.04710648, -0.39054761, -1.37232149],
       [ 0.30422399, -2.05527379,  0.63254817,  0.56952967, -0.16602184,
         0.78253221,  1.49373908,  0.44046077]])

In [ ]:
#Sum 노드
D, N = 8,7
x = np.random.randn(N,D)#입력
y = np.sum(x, axis = 0, keepdims = True)#순전파

dy = np.random.randn(1,D)#무작위 기울기
dx = np.repeat(dy,N,axis = 0)#역전파