In [1]:
import numpy as np
x = np.array([1,2,3])

In [2]:
x.__class__#클래스 이름 표시

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [5]:
W = np.array([[1,2,3],[4,5,6]])

In [6]:
W.shape

(2, 3)

In [7]:
W.ndim

2

In [8]:
W

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
X = [[0,1,2],[3,4,5]]

In [12]:
X

[[0, 1, 2], [3, 4, 5]]

In [10]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
A = np.array([[1,2],[3,4]])

In [14]:
A*10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2],[3,4]])

In [16]:
b = np.array([10,20])

In [17]:
A*b

array([[10, 40],
       [30, 80]])

In [18]:
a = np.array([1,2,3])

In [19]:
b = np.array([4,5,6])

In [20]:
np.dot(a,b)

32

In [22]:
#행렬의 내적
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [23]:
A*B

array([[ 5, 12],
       [21, 32]])

In [24]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])