<a href="https://colab.research.google.com/github/superbunny38/2021DeepLearning/blob/main/pytorch/Chap_2_%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%98_%EA%B5%AC%EC%84%B1%EC%9A%94%EC%86%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!git clone https://github.com/PacktPublishing/Deep-Learning-with-PyTorch-1.x.git book

Cloning into 'book'...
remote: Enumerating objects: 28065, done.
remote: Total 28065 (delta 0), reused 0 (delta 0), pack-reused 28065
Receiving objects: 100% (28065/28065), 132.73 MiB | 27.20 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Checking out files: 100% (28282/28282), done.


In [18]:
%cd /content/book/Chapter02

/content/book/Chapter02


파이토치 텐서 (1차원)

In [1]:
import torch
first_order_tensor = torch.tensor([1,2,3])
print(first_order_tensor)

tensor([1, 2, 3])


In [2]:
first_order_tensor[0]

tensor(1)

In [3]:
first_order_tensor[0:2]

tensor([1, 2])

2차원

In [4]:
second_order_tensor = torch.tensor([[11,12,13],[21,22,23]])

In [5]:
second_order_tensor

tensor([[11, 12, 13],
        [21, 22, 23]])

In [6]:
second_order_tensor[0,1]

tensor(12)

In [8]:
second_order_tensor[:1]

tensor([[11, 12, 13]])

In [13]:
second_order_tensor[1:]

tensor([[21, 22, 23]])

In [14]:
second_order_tensor[:][:1]

tensor([[11, 12, 13]])

4차원 텐서

random

In [68]:
random_tensor = torch.rand([9,1])
random_tensor

tensor([[0.4683],
        [0.2993],
        [0.9436],
        [0.9728],
        [0.8667],
        [0.5587],
        [0.2038],
        [0.1235],
        [0.1745]])

In [71]:
random_tensor.view(-1)

tensor([0.4683, 0.2993, 0.9436, 0.9728, 0.8667, 0.5587, 0.2038, 0.1235, 0.1745])

기본 연산

In [5]:
x = torch.tensor([5,3])
y = torch.tensor([3,2])


In [6]:
x+y

tensor([8, 5])

In [8]:
torch.add(x,y)

tensor([8, 5])

In [9]:
x*y

tensor([15,  6])

In [10]:
torch.mul(x,y)

tensor([15,  6])

In [11]:
x@y

tensor(21)

In [12]:
torch.matmul(x,y)

tensor(21)

In [13]:
x.dtype

torch.int64

In [14]:
y.dtype

torch.int64

In [15]:
torch.FloatTensor([5,3])

tensor([5., 3.])

In [16]:
x.type(torch.DoubleTensor)

tensor([5., 3.], dtype=torch.float64)

## 파이토치 텐서로 데이터셋 가져오기

In [74]:
import numpy as np
admit_data = np.genfromtxt("admit_status.csv",
                           delimiter = ",",
                           skip_header = 1)
print(admit_data)

[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]
 [  1.   760.     3.     2.  ]
 [  1.   560.     2.98   1.  ]
 [  0.   400.     3.08   2.  ]
 [  1.   540.     3.39   3.  ]]


In [75]:
admit_tensor = torch.from_numpy(admit_data)

In [76]:
admit_tensor

tensor([[  0.0000, 380.0000,   3.6100,   3.0000],
        [  1.0000, 660.0000,   3.6700,   3.0000],
        [  1.0000, 800.0000,   4.0000,   1.0000],
        [  1.0000, 640.0000,   3.1900,   4.0000],
        [  0.0000, 520.0000,   2.9300,   4.0000],
        [  1.0000, 760.0000,   3.0000,   2.0000],
        [  1.0000, 560.0000,   2.9800,   1.0000],
        [  0.0000, 400.0000,   3.0800,   2.0000],
        [  1.0000, 540.0000,   3.3900,   3.0000]], dtype=torch.float64)

In [91]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class MyNeuralNet(nn.Module):
    def __init__(self, input_size, n_nodes, output_size):
        super(MyNeuralNet, self).__init__()
        self.operationOne = nn.Linear(input_size, n_nodes)
        self.operationTwo = nn.Linear(n_nodes, output_size)
    def forward(self, x):
        x = F.relu(self.operationOne(x))
        x = self.operationTwo(x)
        x = F.sigmoid(x)
        #x = x.view(-1)#이러면 되나
        return x

In [78]:
my_network = MyNeuralNet(input_size = 3, n_nodes = 2, output_size = 1)

훈련 데이터셋과 테스트 데이터셋으로 나누기

In [79]:
x_train = admit_tensor[:300, 1:].float()
y_train = admit_tensor[:300, 0].float()
x_test = admit_tensor[300:, 1:].float()
y_test = admit_tensor[300:, 0].float()

In [80]:
#2진 분류에 사용되는 binary cross-entropy loss
criterion = nn.BCELoss()

In [81]:
my_network.parameters()

<generator object Module.parameters at 0x7fc198777c50>

In [82]:
optimizer = torch.optim.SGD(my_network.parameters(), lr = 0.01)

In [92]:
for epoch in range(100):
  #Forward Propagation
  y_pred = my_network(x_train)

  #Compute and print loss
  loss_score = criterion(y_pred, y_train)
  print("epoch: ",epoch, "loss: ",loss_score.item())

  #zero the gradients(refresh)
  optimizer.zero_grad()
  
  #perform a backward pass(backpropagation)
  loss_score.backward()

  #update parameters
  optimizer.step()

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


epoch:  0 loss:  35.53474807739258
epoch:  1 loss:  35.53474807739258
epoch:  2 loss:  35.53474426269531
epoch:  3 loss:  35.534732818603516
epoch:  4 loss:  35.534725189208984
epoch:  5 loss:  35.534725189208984
epoch:  6 loss:  35.53471374511719
epoch:  7 loss:  35.53471374511719
epoch:  8 loss:  35.534706115722656
epoch:  9 loss:  35.534706115722656
epoch:  10 loss:  35.53469467163086
epoch:  11 loss:  35.53468322753906
epoch:  12 loss:  35.53468322753906
epoch:  13 loss:  35.5346794128418
epoch:  14 loss:  35.534671783447266
epoch:  15 loss:  35.53466796875
epoch:  16 loss:  35.53466033935547
epoch:  17 loss:  35.53465270996094
epoch:  18 loss:  35.53465270996094
epoch:  19 loss:  35.53464889526367
epoch:  20 loss:  35.534637451171875
epoch:  21 loss:  35.53463363647461
epoch:  22 loss:  35.534629821777344
epoch:  23 loss:  35.53462219238281
epoch:  24 loss:  35.53461456298828
epoch:  25 loss:  35.534610748291016
epoch:  26 loss:  35.534603118896484
epoch:  27 loss:  35.53459930419

원래 학습 안되는게 정상

In [85]:
import numpy as np
admit_data = np.genfromtxt('admit_status.csv', delimiter = ',', skip_header = 1)
print(admit_data)

[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]
 [  1.   760.     3.     2.  ]
 [  1.   560.     2.98   1.  ]
 [  0.   400.     3.08   2.  ]
 [  1.   540.     3.39   3.  ]]


In [86]:
admit_tensor = torch.from_numpy(admit_data)
print(admit_tensor)

tensor([[  0.0000, 380.0000,   3.6100,   3.0000],
        [  1.0000, 660.0000,   3.6700,   3.0000],
        [  1.0000, 800.0000,   4.0000,   1.0000],
        [  1.0000, 640.0000,   3.1900,   4.0000],
        [  0.0000, 520.0000,   2.9300,   4.0000],
        [  1.0000, 760.0000,   3.0000,   2.0000],
        [  1.0000, 560.0000,   2.9800,   1.0000],
        [  0.0000, 400.0000,   3.0800,   2.0000],
        [  1.0000, 540.0000,   3.3900,   3.0000]], dtype=torch.float64)


In [87]:
x_train = admit_tensor[:300, 1:].float()
y_train = admit_tensor[:300, 0].float()
x_test = admit_tensor[300:, 1:].float()
y_test = admit_tensor[300:, 0].float()

In [88]:
criterion = nn.BCELoss()

In [89]:
optimizer = torch.optim.SGD(my_network.parameters(), lr=0.01)

In [93]:
for epoch in range(100):
    y_pred = my_network(x_train)
    loss_score = criterion(y_pred, y_train)
    print('epoch: ', epoch, 'loss: ', loss_score)
    
    optimizer.zero_grad()
    loss_score.backward()
    optimizer.step()

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


epoch:  0 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  1 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  2 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  3 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  4 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  5 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  6 loss:  tensor(35.5342, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  7 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  8 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  9 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  10 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  11 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  12 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropyBackward0>)
epoch:  13 loss:  tensor(35.5341, grad_fn=<BinaryCrossEntropy